# Generated by Django 4.1.7 on 2023-05-23 13:52

from django.db import migrations, models
import django.db.models.deletion
import expenses.models
import expenses.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='electricity_readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reading_1', models.IntegerField()),
                ('reading_2', models.IntegerField()),
                ('submitted', models.BooleanField(default=False)),
                ('annual_statement', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='expense_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='expense category', max_length=1000)),
                ('frequency', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['frequency'],
            },
        ),
        migrations.CreateModel(
            name='gas_readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reading', models.IntegerField()),
                ('submitted', models.BooleanField(default=False)),
                ('annual_statement', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ing_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleansed', models.BooleanField(default=False)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(blank=True, help_text='ING bank statements', null=True, storage=expenses.storage.OverwriteStorage(), upload_to=expenses.models.statement_fn)),
            ],
            options={
                'verbose_name': 'ING statement',
                'verbose_name_plural': 'ING statements',
                'ordering': ['-generated_on'],
            },
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.TextField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, help_text='enter a description', max_length=1000, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='category', to='expenses.expense_category')),
            ],
            options={
                'ordering': ['-date', 'category', 'name'],
            },
        ),
    ]
